### PR TITLE
testing cicd

### PR DESCRIPTION
**Pull request by gogo2464**
- [X] issue #https://github.com/keep-starknet-strange/blobstream-starknet/issues/136
- [X] follows contribution [guide](https://github.com/keep-starknet-strange/blobstream-starknet/blob/main/CONTRIBUTING.md)
- [X] code change includes tests
- [ ] breaking change

Does not compile on windows. Should I document it?

Reday for a review.

### CODE REVIEW

**Comment by gogo2464** [comment]
still ready for a review

**Comment by gogo2464** [comment]
My bad. I deleted some files by mistake!

**Review by drspacemn — COMMENTED** [review]
the ci action looks good, but it appears something happened with the README in your PR. Can you clean this before we merge this?

**Comment by gogo2464** [comment]
I added a few lines in the readme: https://github.com/keep-starknet-strange/blobstream-starknet/pull/141/files#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5R25 

sadly the crlf seems wrong :/

**Comment by gogo2464** [comment]
I will look for the git command to remove crlf on windows tommowor.

**Comment by gogo2464** [comment]
I did:

```
git config --global core.autocrlf true
git config --global core.safecrlf false
```

did not changed nothing. any idea of why?

**Comment by gogo2464** [comment]
pleeeeease!!

**Comment by drspacemn** [comment]
Looks like the README is still edited in the PR. Maybe just create a clean branch and only commit the cicd file?

**Comment by drspacemn** [comment]
If you need I can create a new PR and just update it with your git action. You will still get paid for the contribution through OnlyDust. lmk

**Comment by gogo2464** [comment]
Hello.

I absolutely ignored that I could be paid by only dust. if really you want I could git clone my own fork and try harder.

If it is eady for you to do it, you can do it.

Thank you very much :)

**Comment by gogo2464** [comment]
@drspacemn it is ok if you can author me. thanks :)

**Comment by gogo2464** [comment]
@drspacemn can I get news please?

**Comment by gogo2464** [comment]
@drspacemn I do not have any news. can I continue the PR alone finally then please? I do not want to override your work.

**Comment by gogo2464** [comment]
Hello.

As mentionned in private, I would like to know if I can finish it alone or if it will bother you because you could be still busy to do it alone by yourself.

I do not want to overrride your work.

**Comment by drspacemn** [comment]
Sorry for the delay. I have not done the work so feel free to complete yourself.

**Comment by gogo2464** [comment]
I am going to do it.

**Comment by gogo2464** [comment]
ready to merge!

**Comment by drspacemn** [comment]
nice work, thank you!

**Pull request merged**
